### ISSUE TITLE
Broken in Firefox

### ISSUE THREAD

**Issue by Acarii** [iblobtouch/iblobtouch.github.io#17]
User ScarXLXX has reported that the program is broken in firefox. 

This is what it looks like for firefox: http://i.imgur.com/APr0YLu.png (text areas are broken)

This is what it looks like for Chrome: http://i.imgur.com/wqkor1h.png (Correct)

**Comment by Acarii** [comment]
I don't know yet how to fix this myself, so I'm setting it as an issue until someone has a solution.

**Comment by ScarXLXX** [comment]
Yeah it is broken. I hate using Chrome but It'll do for a while I guess.

**Comment by Acarii** [comment]
I've got part of it solved, but nothing yet on the #notes area yet.

**Comment by Acarii** [comment]
Okay, I am pretty sure I know what the problem is. Fixing it is still out of my hands, but I'll get around to it soon i hope.

problem is the whitespace between lines varies between browsers. I need to set it through the CSS. i don't know how to do this tho.

**Comment by ScarXLXX** [comment]
I'd like to say Im going to comment on commits from now, and open an issue if there is a bug or something. So be sure to check the comments more.

**Comment by aryamanarora** [comment]
@ScarXLXX Emails are sent for each comment

**Comment by ScarXLXX** [comment]
Oh that's good, thanks for telling me

**Comment by Acarii** [comment]
Found a solution, just making sure it works as I believe before I submit it.
