### ISSUE TITLE
How..

### ISSUE THREAD

**Issue by iLoveOverseer** [iblobtouch/iblobtouch.github.io#27]
i am new here, and i dunno how i go straight to building, i am just lost right now, i don't know what to do and how you get there.

**Comment by iLoveOverseer** [comment]
like, how do i ''open'' the tank builder :/

**Comment by Blockguy24** [comment]
Go to:
[https://iblobtouch.github.io/](https://iblobtouch.github.io/)

Then click Edit Mode.

**Comment by Acarii** [comment]
**If you're asking how to edit FTB to add new features:** 

Create a fork, then change the name of the fork to iLoveOverseer.github.io. 

Then you can open https://iLoveOverseer.github.io/ in Chrome and make tweaks to the code through the developer tools. When you've made a tweak that you feel is good and won't crash, copy it to the respective file on your fork "iLoveOverseer.github.io". If you feel the changes are something that belongs in the public release, push the changes to us.

---

**If you're asking how to use FTB and create new tanks:**

Blockguy24 already answered.

---

That said, don't think the issues section should be a discussion area. If you still need help, post in https://reddit.com/r/diepioFTB/
