### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by GhostShot3** [iblobtouch/iblobtouch.github.io#3]
How to enable "Auto Fire" and "Auto spin" ?

**Comment by iblobtouch** [comment]
Same controls as in the regular game.

**Comment by GhostShot3** [comment]
Wich key active it ?

**Comment by aryamanarora** [comment]
@GhostShot3 
E=auto fire 
C=auto spin

**Comment by GhostShot3** [comment]
@aryamanarora Thx.
