### ISSUE TITLE
Please read and reply

### ISSUE THREAD

**Issue by Leviterminator** [iblobtouch/iblobtouch.github.io#38]
I know, i asked this a lot: when will be the auto turrets in the game? I am a fan if this awesome tanks creator, and i just don't understand why is the auto turret not in the game. And you did not answer my previous question, so please, at least tell me, what is the problem with the auto turret, or what is the problem with adding it.

**Comment by ScarXLXX** [comment]
They are in the game now but they are kinda buggy.
