### ISSUE TITLE
New cannons for tanks 

### ISSUE THREAD

**Issue by Iblobtouchfan** [iblobtouch/iblobtouch.github.io#49]
We have most types of cannons in iblobtouch but we are missing a one.
The machine gun.
I try to improvise by make a "bigger cannon" and messing around in the bullet options making the bullet smaller. and increasing the spread. but in the end its just ugly. 
it just looks like a destroyer cannon pretending to be a machine gun.
so im asking for you to make a machine gunner cannon that has spread and a funnel shaped muzzle. 
Please? ;3

**Comment by Acarii** [comment]
Closed. Functionality exists with existing barrels.

Use a disabled drone cannon with negitive Y values laying on top of the functional normal barrel. Spread functionality already exists.
