### ISSUE TITLE
add sounds

### ISSUE THREAD

**Issue by ArchVivi** [iblobtouch/iblobtouch.github.io#59]
add sounds when you shoot the sound is MLG hitmarker

**Comment by DogeisCut** [comment]
this is based of diep.io that has no sounds!

**Comment by Acarii** [comment]
There are no sounds in diep.io, and despite my interest in adding support for other .io games like doblons.io, those games also lack sound. Sound support is firmly not planned.

There is also the matter of who owns the sound, licencing, and use cases. We might not be able to even use sound even if it is added to the game.

**Comment by ArchVivi** [comment]
add something like coloring to the background

**Comment by aryamanarora** [comment]
@ZmanGamer again, this is based off of diep.io

**Comment by Acarii** [comment]
I at one point actually wanted to do just that, but I couldn't quite get it working the way I wanted. 

The plan was to introduce a screenshot mode, a special option that allowed you to control the background, defaulting to greenscreen green.

When I originally tried implementing it, I think it was a matter of just not knowing enough. I think if I tried again I could, but I've very little interest in such a feature, especially with the number of bugs piling up that seem to just break worse when I make attempts at fixing them on my private version.
