### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by SalreixVonOtsuu** [iblobtouch/iblobtouch.github.io#6]
There seems to be a bug with damage possibly, when it gets down to the last bit of health shapes are indestructible.

**Comment by SalreixVonOtsuu** [comment]
![image](https://cloud.githubusercontent.com/assets/22205962/18532982/91605c7e-7a94-11e6-9f08-624000754c27.png) Screenshot

**Comment by SalreixVonOtsuu** [comment]
![image](https://cloud.githubusercontent.com/assets/22205962/18533013/d3412a7e-7a94-11e6-86b3-bc0a6f7ed92b.png)
Another screen shot next image is what happens next.
![image](https://cloud.githubusercontent.com/assets/22205962/18533027/ec999f74-7a94-11e6-95ac-25cd9b794d03.png)

**Comment by iblobtouch** [comment]
Fixed, thanks for reporting
